name: Print  workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: cloud-dev-user/testdemo@master
        with:
          message: "Hello, world!"
